# Name of your dbt project
name: 'atmosync_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which profile to use from profiles.yml
profile: 'atmosync_profile'

# Paths for various dbt folders
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring model folders and default materializations
models:
  atmosync_dbt:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts

# Project-wide variables for decay math and business logic thresholds
vars:
  spoilage_arbitrage_threshold: 500.00
  opt_temp: 5.0
  opt_humidity: 85.0
  k_t: 0.08
  k_h: 0.02
  base_decay_rate: 0.005
